# Generated by Django 4.1.6 on 2023-02-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.TimeField(max_length=6, verbose_name='time')),
                ('periodicity', models.CharField(choices=[('daily', 'Once a day'), ('weakly', 'Once a weak'), ('monthly', 'Once a month')], max_length=9)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('created', 'Created'), ('started', 'Started')], default='created', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('body', models.TextField(max_length=2000, verbose_name='Message body')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='time')),
                ('status', models.CharField(max_length=254)),
                ('response', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
