# Generated by Django 4.1.6 on 2023-02-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
