# Generated by Django 4.1.6 on 2023-02-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_distribution_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'permissions': (('deactivate_user', 'can deactivate user'), ('change_is_active', 'can deactivate distribution'))},
        ),
    ]
