# Generated by Django 4.1.6 on 2023-02-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.CharField(max_length=400, verbose_name='content')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('status', models.BooleanField(default=True, verbose_name='is_published')),
                ('views', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='просмотров')),
            ],
        ),
    ]
